#!/usr/bin/env python3
# ============================================================
#   THE DECK, IN ITS OWN COLOURS
#
#   Pamela Colman Smith drew the seventy-eight cards Rider published in
#   1909, and they were printed in flat colour: yellow skies, a red cloak,
#   the blue of the pool under the Star. An earlier version of this file
#   carried vector tracings of those drawings, which were faithful to the
#   line and lost everything else — black ink on cream, correct and dead.
#   Colour is not decoration on these cards. The suits are colours, the
#   elements are colours, and a reader looks at the yellow before they
#   read the title.
#
#   So: the scans themselves, at the size the app actually draws them,
#   in WebP, as data URIs. The source is 300x527 per card and about
#   twenty-two megabytes for the deck, which is five times the whole of
#   this house; 176 wide at quality 70 is a little under nine hundred
#   kilobytes for all seventy-eight, which the single file can carry.
#
#   Run it by hand when the source changes; the output is committed, so a
#   normal build never needs it, and neither Pillow nor the source deck
#   is a dependency of anything else here:
#
#     pip install Pillow
#     npm pack @cometpisces/tarot-kit-images && tar xzf *.tgz
#     python3 tools/build-tarot-art.py package/images
#
#   Source of the scans: the images bundled with the npm package
#   @cometpisces/tarot-kit-images, whose LICENSE.md states the artwork to
#   be public domain. It is: the deck was published in 1909 and Smith
#   died in 1951, so both the drawings and faithful photographs of them
#   are out of copyright.
# ============================================================
import io, os, sys, base64, gzip

try:
    from PIL import Image
except ImportError:
    sys.exit('needs Pillow:  pip install Pillow')

WIDTH   = int(os.environ.get('W', 176))   # the card is drawn 160 wide; a little over is for the directory
QUALITY = int(os.environ.get('Q', 70))    # below ~64 the fine engraving lines start to smear

# the deck in the order TAROT holds it: twenty-two majors, then wands,
# cups, swords, pentacles, ace to king. Waite's numbering, so Strength is
# eight and Justice eleven.
MAJORS = ['TheFool', 'TheMagician', 'TheHighPriestess', 'TheEmpress', 'TheEmperor',
          'TheHierophant', 'TheLovers', 'TheChariot', 'Strength', 'TheHermit',
          'WheelOfFortune', 'Justice', 'TheHangedMan', 'Death', 'Temperance',
          'TheDevil', 'TheTower', 'TheStar', 'TheMoon', 'TheSun', 'Judgement', 'TheWorld']
ORDER = [f'{i:02d}-{n}' for i, n in enumerate(MAJORS)]
for suit in ('Wands', 'Cups', 'Swords', 'Pentacles'):
    ORDER += [f'{suit}{i:02d}' for i in range(1, 15)]   # 11-14 are page, knight, queen, king


def render(path):
    """One card: flattened onto white, scaled down, encoded."""
    im = Image.open(path).convert('RGBA')
    # the scans have transparent rounded corners with junk in the colour
    # channels underneath; compositing rather than dropping alpha keeps
    # that junk from surfacing as four dark specks
    im = Image.alpha_composite(Image.new('RGBA', im.size, (255, 255, 255, 255)), im).convert('RGB')
    h = round(im.height * WIDTH / im.width)
    buf = io.BytesIO()
    im.resize((WIDTH, h), Image.LANCZOS).save(buf, 'WEBP', quality=QUALITY, method=6)
    return buf.getvalue(), h


def main():
    if len(sys.argv) < 2:
        sys.exit('usage: python3 tools/build-tarot-art.py <dir of 00-TheFool.png …>')
    src = sys.argv[1]
    raw_in = raw_out = 0
    heights, b64s = set(), []
    for name in ORDER:
        f = os.path.join(src, name + '.png')
        raw_in += os.path.getsize(f)
        data, h = render(f)
        raw_out += len(data)
        heights.add(h)
        b64s.append(base64.b64encode(data).decode('ascii'))

    body = '''/* ============================================================
   THE PICTURES

   Pamela Colman Smith's drawings for the deck Rider published in 1909 —
   the ones everybody means by "the tarot" — in the colours they were
   printed in, scaled to the size the app draws them and encoded as WebP.
   They are in the public domain: published 1909, and Smith died in 1951.

   One image per card, in the order TAROT holds them: the twenty-two
   Major Arcana, then Wands, Cups, Swords and Pentacles, ace to king.
   Bare base64 — tarotArtURL() puts the data: prefix back on, which is
   seventy-eight repetitions of the same twenty-three characters saved.

   Generated by tools/build-tarot-art.py — do not edit by hand.
   ============================================================ */
const TAROT_ART_W = %d, TAROT_ART_H = %d;
const TAROT_ART = [
%s
];
''' % (WIDTH, sorted(heights)[-1],
       '\n'.join(f'/* {n} */ "{b}",' for n, b in zip(ORDER, b64s)))

    out = os.path.join(os.path.dirname(__file__), '..', 'src', '16-divination-art.js')
    with open(out, 'w') as fh:
        fh.write(body)

    mb = lambda n: n / 1048576
    gz = len(gzip.compress(body.encode(), 9))
    print(f'in    {mb(raw_in):.2f} MB of scans')
    print(f'out   {mb(len(body)):.2f} MB written, {mb(gz):.2f} MB gzipped')
    print(f'      {WIDTH}x{sorted(heights)[-1]} at quality {QUALITY}, {raw_out / len(ORDER) / 1024:.1f} KB a card')
    print(f'→ {os.path.normpath(out)}')


if __name__ == '__main__':
    main()
