/* ============================================================
   SEED — the house is furnished on first open
   ============================================================ */
function seed(){
  const T = today(); const ago = n => addDays(T, -n);
  let rs = 7; const rnd = () => { rs = (rs*1103515245 + 12345) & 0x7fffffff; return rs/0x7fffffff; };
  const ts = n => new Date(parseDay(ago(n)).getTime()+9*3600000).toISOString();

  const stages = [
    {id:'s1',num:1,char:'野',name:'Wild',tagline:'Play as the whole point.',hue:'#d4a44c',years:'1998–2005',
      narrative:"Before there were rules there was the courtyard, and the courtyard had no edges. I remember the smell of rain on hot concrete and the exact weight of a stolen mango. Nobody asked what I was going to become. I was already becoming it, on all fours, under the neighbour's fence.\n\nWhat I tell myself now is that this was the last time attention was free — that I gave it to whatever was in front of me without being told where it belonged. Everything since has been a negotiation with that child.",
      narrativeHistory:[{date:ago(410),text:"A happy childhood, mostly. Lots of running around. Nothing much to say about it — the interesting part of my life started later."}],
      substages:[{id:'s1a',name:'The courtyard years',desc:'Grandmother\'s house. Three generations, one kitchen, a gate that was never locked.',photos:[]},{id:'s1b',name:'First school',desc:'The uniform itched. The first friend was a boy who could whistle through a blade of grass.',photos:[]}],
      photos:[],soundtrack:[{t:'Teresa Teng — 月亮代表我的心'},{t:'The cassette my mother sang along to in the car'},{t:'Cicadas (not a song, but the sound of that whole era)'}],
      artifacts:[{id:'a1',caption:'Kindergarten report: "talks to plants"',date:'2003',src:''},{id:'a2',caption:'Ticket stub, first cinema visit',date:'2004',src:''}],
      letters:{to:"You don't know it yet, but you're the one I keep going back to for instructions. When I don't know what I want, I ask what you'd have chased across the yard. Keep the mango. Keep the fence.",from:"Why are you sitting inside? It's not raining. Come outside. What are you waiting for — permission?"},
      retroValues:{'v-wisdom':30,'v-auth':92,'v-conn':80,'v-free':95,'v-creat':88,'v-exp':70,'v-health':85,'v-spirit':60,'v-awe':98,'v-indep':40}},
    {id:'s2',num:2,char:'规',name:'Rule',tagline:'Obedience, and the medals it won.',hue:'#a0855a',years:'2005–2012',
      narrative:"The medals were real and so was the cost. I learned that being good was a currency, and I was good at earning it: neat handwriting, first to raise a hand, the child teachers pointed at. I got very skilled at reading a room for what it wanted from me before I knew what I wanted from myself.\n\nThe story I tell now is that this stage installed my most useful and most dangerous skill — the ability to perform excellence on demand. It got me everywhere I went next. It also meant I didn't ask, for a long time, whether I wanted to go there.",
      narrativeHistory:[{date:ago(700),text:"I was a good student. I worked hard and it paid off. I'm grateful to my parents for the discipline — it's the foundation of everything."}],
      substages:[{id:'s2a',name:'The piano years',desc:'Grade exams every year. I hated the metronome and loved the certificates.',photos:[]},{id:'s2b',name:'Olympiad',desc:'Maths competitions. The first time strangers clapped for me. I was hooked on it for a decade.',photos:[]},{id:'s2c',name:'Prefect',desc:'The badge. The responsibility of telling other children what to do, and finding I was good at it.',photos:[]}],
      photos:[],soundtrack:[{t:'Chopin — Nocturne Op. 9 No. 2 (the exam piece)'},{t:'Jay Chou — 七里香'},{t:'School bell, 7:20am'}],
      artifacts:[{id:'a3',caption:'Piano Grade 5 certificate',date:'2009',src:''},{id:'a4',caption:'Letter from the headmaster',date:'2011',src:''}],
      letters:{to:"I know the medal feels like love. I'm not going to tell you it isn't — some of it is. But there's a version of you that plays piano when nobody is listening, and I need you to protect him.",from:"Did it work? Did we get in? Did they say we were good? Tell me it was worth it."},
      retroValues:{'v-wisdom':40,'v-auth':35,'v-conn':55,'v-free':25,'v-creat':40,'v-exp':35,'v-health':70,'v-spirit':30,'v-awe':45,'v-indep':30}},
    {id:'s3',num:3,char:'独',name:'Solitude',tagline:'Fifteen. Alone. Turning inward for the first time.',hue:'#6b7f8e',years:'2013–2014',
      narrative:"This was the year the world got quieter. Not because anything went silent, but because I started listening to a different frequency — one that only played when no one else was around. I read everything. I walked home the long way. I discovered that my own company had a texture, and that the texture was not loneliness but something closer to a door.\n\nI think of this year now as the year I was born a second time — quietly, without witnesses. Every important decision since has been made by the person who first appeared on those long walks.",
      narrativeHistory:[],
      substages:[{id:'s3a',name:'The long walks',desc:'Forty minutes each way, by choice. Headphones. The route past the river.',photos:[]},{id:'s3b',name:'The notebooks',desc:'Eleven of them. Mostly unreadable now. The first time I wrote to find out what I thought.',photos:[]}],
      photos:[],soundtrack:[{t:'Radiohead — How to Disappear Completely'},{t:'Bon Iver — Holocene'},{t:'Ryuichi Sakamoto — Merry Christmas Mr. Lawrence'}],
      artifacts:[{id:'a5',caption:'Notebook #4, page with the list of "things I actually like"',date:'2013',src:''}],
      letters:{to:"You are not broken and you are not behind. The quiet is the point. In ten years you will build an entire house around the thing you found this year.",from:"I found something. I don't know what to call it. Do you still have it? Please tell me you didn't lose it to become impressive again."},
      retroValues:{'v-wisdom':60,'v-auth':70,'v-conn':25,'v-free':45,'v-creat':65,'v-exp':30,'v-health':50,'v-spirit':65,'v-awe':70,'v-indep':75}},
    {id:'s4',num:4,char:'追',name:'Clout',tagline:'Papers, exams, a pandemic, a way out.',hue:'#c47832',years:'2015–2020',
      narrative:"I chased. Grades, then admissions, then the next thing with a name on it. I was very good at the chase and I confused being good at it with wanting the prize. The pandemic arrived like a held breath, and in the stillness I noticed the machine kept running with no one at the wheel.\n\nThe story I tell now: this stage was an escape velocity calculation. I needed enough credentials to leave, and I got them. What I didn't budget for was that the person who left would need to be reintroduced to himself on arrival.",
      narrativeHistory:[{date:ago(520),text:"University was intense but I got through it. The pandemic was hard on everyone. I graduated with a strong record and options."}],
      substages:[{id:'s4a',name:'Exam machine',desc:'Two years of pure optimisation. I could predict the paper. I stopped reading for pleasure.',photos:[]},{id:'s4b',name:'Lockdown',desc:'Four walls, a laptop, and the sudden, embarrassing question of what I do when nobody is watching.',photos:[]},{id:'s4c',name:'The application',desc:'Personal statements. I wrote a self I could sell, then had to live inside it.',photos:[]}],
      photos:[],soundtrack:[{t:'Frank Ocean — Nights'},{t:'Phoebe Bridgers — I Know the End'},{t:'The Zoom "you are muted" chime'}],
      artifacts:[{id:'a6',caption:'Acceptance email, printed and folded',date:'2020',src:''},{id:'a7',caption:'Pandemic mask, first one',date:'2020',src:''}],
      letters:{to:"Slow down. You're going to win, and it's not going to feel like you think. Read one book this year that isn't on any list.",from:"I don't have time for this. Tell me the exam is worth it and let me get back to work."},
      retroValues:{'v-wisdom':50,'v-auth':40,'v-conn':45,'v-free':30,'v-creat':30,'v-exp':40,'v-health':35,'v-spirit':25,'v-awe':35,'v-indep':60}},
    {id:'s5',num:5,char:'法',name:'Law',tagline:'A future that fit on paper and nowhere else.',hue:'#8a8d8f',years:'2020–2022',
      narrative:"Law was the correct answer to a question nobody had asked me. It was rigorous, respectable, and it fit perfectly on paper — my parents' paper, my CV's paper, the paper of the person I'd been trained to be. I was competent at it. I was also, for the first time in my life, bored in a way that felt structural rather than temporary.\n\nThe story I tell now is that this was the most important failure of my life. I learned what it feels like to be excellent at something that is killing you slowly, and I learned to trust that feeling over any credential.",
      narrativeHistory:[{date:ago(900),text:"Law school. A sensible choice, a good career path. It's demanding but I'm managing. Not sure it's for me but it's too early to tell."}],
      substages:[{id:'s5a',name:'Moot court',desc:'I won. I felt nothing. That was the data point.',photos:[]},{id:'s5b',name:'The internship',desc:'Twelve-hour days in a glass building. The senior partner had a boat and no light in his eyes.',photos:[]}],
      photos:[],soundtrack:[{t:'Nils Frahm — Says'},{t:'Mitski — Nobody'},{t:'Fluorescent hum, 47th floor'}],
      artifacts:[{id:'a8',caption:'Internship lanyard',date:'2022',src:''}],
      letters:{to:"The boredom is information. It's the most honest thing your body has said to you in years. Listen before you're 35.",from:"Everyone says I've made it. Why does made-it feel like a waiting room?"},
      retroValues:{'v-wisdom':55,'v-auth':25,'v-conn':40,'v-free':20,'v-creat':15,'v-exp':30,'v-health':30,'v-spirit':20,'v-awe':20,'v-indep':45}},
    {id:'s6',num:6,char:'游',name:'Wander',tagline:'Everything I could get my hands on.',hue:'#7f916a',years:'2022–2024',
      narrative:"I left. Not dramatically — a deferred offer, a one-way ticket, a spreadsheet of hostels. Then I said yes to everything: a kitchen in Lisbon, a night shift behind a bar in Osaka, three months learning to climb badly in Yangshuo, a photography gig I was not qualified for. I built nothing and I learned everything.\n\nThe story I tell now is that this stage was a massive, deliberate exposure to experience — the value I'd starved for a decade, eaten in one sitting. It gave me a body of raw material. What it didn't give me was a shape, and by the end I could feel myself wanting one.",
      narrativeHistory:[],
      substages:[{id:'s6a',name:'Lisbon kitchen',desc:'Six months of prep work. Onions, mostly. The head chef taught me that speed is a form of attention.',photos:[]},{id:'s6b',name:'Osaka nights',desc:'The bar in Namba. Where the Tokyo dream was actually born, at 3am, wiping a counter.',photos:[]},{id:'s6c',name:'Yangshuo',desc:'Limestone karst, chalk, fear. The first sport I chose for myself as an adult.',photos:[]}],
      photos:[],soundtrack:[{t:'Fishmans — Long Season'},{t:'Khruangbin — Maria También'},{t:'Haruomi Hosono — Sports Men'}],
      artifacts:[{id:'a9',caption:'Bar tab from the Namba bar, my first shift',date:'2023',src:''},{id:'a10',caption:'Climbing guidebook, water-damaged',date:'2023',src:''}],
      letters:{to:"Yes to all of it. But start writing down what each yes teaches you, because in two years you'll want to know which of them were the real ones.",from:"I'm in a kitchen in Lisbon and my hands smell like garlic and I've never been happier. Tell me you didn't go back to the glass building."},
      retroValues:{'v-wisdom':60,'v-auth':75,'v-conn':60,'v-free':90,'v-creat':70,'v-exp':98,'v-health':65,'v-spirit':50,'v-awe':85,'v-indep':80}},
    {id:'s7',num:7,char:'鏡',name:'Mirror',tagline:'Learning to love, learning to be met.',hue:'#a0727e',years:'2024–2026',
      narrative:"Someone saw me and did not look away. That sounds simple and it undid me. For the first time, another person's attention wasn't a medal to win or a room to read — it was a mirror I could stand in front of without performing. I learned that I'd been treating intimacy as an exam. I learned what it costs to be met, and that I'd been avoiding the cost for years.\n\nThe story I tell now is that this stage taught me the difference between being impressive and being known. I'm still learning it. I suspect I'll be learning it for the rest of my life.",
      narrativeHistory:[{date:ago(200),text:"Met someone. It's going well. I'm trying not to overthink it, which is hard for me."}],
      substages:[{id:'s7a',name:'The first winter',desc:'Two people, one small apartment, a lot of learning how to argue.',photos:[]},{id:'s7b',name:'Meeting the family',desc:'Hers, then mine. Watching each other be someone\'s child.',photos:[]}],
      photos:[],soundtrack:[{t:'Big Thief — Change'},{t:'Ichiko Aoba — Porcelain'},{t:'The rice cooker song'}],
      artifacts:[{id:'a11',caption:'First note left on the kitchen table',date:'2024',src:''}],
      letters:{to:"You're going to want to run when it gets close. Don't. The thing you found in Solitude is not threatened by this; it's finally being witnessed.",from:"It's terrifying. Is it supposed to be this terrifying? Did we stay?"},
      retroValues:{'v-wisdom':65,'v-auth':72,'v-conn':85,'v-free':60,'v-creat':55,'v-exp':60,'v-health':58,'v-spirit':62,'v-awe':70,'v-indep':55}},
    {id:'s8',num:8,char:'未',name:'Not Yet',tagline:'Tokyo. A bar. A life I build myself.',hue:'#b08968',years:'2026–',
      narrative:"This is the room that isn't built. A bar with eleven seats in Kagurazaka. A master's degree I'm actually curious about. A language in which I can be funny. A body I don't have to apologise to. A family, maybe — the word still catches in my throat, which is how I know it matters.\n\nThe story I tell about the future is the one I'm writing in the Vision Tree. This stage stays open. That's the point.",
      narrativeHistory:[],
      substages:[{id:'s8a',name:'not yet',desc:'',photos:[]}],
      photos:[],soundtrack:[{t:'(to be discovered)'}],artifacts:[],
      letters:{to:'',from:''},retroValues:{}},
  ];

  const threads = [
    {id:'t-approval',name:'Approval',desc:'The need to be told I did well. Installed early, still running.',color:'#d4a44c',status:'active'},
    {id:'t-escape',name:'Escape',desc:'Leaving as a solution. Countries, careers, relationships.',color:'#6b7f8e',status:'transmuted'},
    {id:'t-seen',name:'Being Seen',desc:'The hunger to be witnessed without performing.',color:'#a0727e',status:'active'},
    {id:'t-rigour',name:'Rigour vs. Play',desc:'The oscillation between the metronome and the courtyard.',color:'#7f916a',status:'active'},
    {id:'t-leaving',name:'Leaving',desc:'Every ending I chose before it was chosen for me.',color:'#8a8d8f',status:'dormant'},
  ];
  const tensions = [
    {id:'tn1',left:'Freedom',right:'Rootedness',threadId:'t-escape',log:[{date:ago(1400),pos:85,note:'Wander, peak'},{date:ago(700),pos:70,note:''},{date:ago(300),pos:55,note:'Mirror shifts this'},{date:ago(20),pos:48,note:'Tokyo would be both'}]},
    {id:'tn2',left:'Rigour',right:'Play',threadId:'t-rigour',log:[{date:ago(2500),pos:15,note:'Rule'},{date:ago(1400),pos:75,note:''},{date:ago(30),pos:50,note:'finally oscillating on purpose'}]},
    {id:'tn3',left:'Exposure',right:'Depth',threadId:null,log:[{date:ago(1200),pos:10,note:'everything, everywhere'},{date:ago(60),pos:62,note:'wanting one thing well'}]},
    {id:'tn4',left:'Independence',right:'Belonging',threadId:'t-seen',log:[{date:ago(3000),pos:20,note:''},{date:ago(1500),pos:10,note:''},{date:ago(100),pos:55,note:''}]},
    {id:'tn5',left:'Ambition',right:'Presence',threadId:'t-approval',log:[{date:ago(2000),pos:10,note:'Clout'},{date:ago(400),pos:45,note:''},{date:ago(10),pos:52,note:''}]},
  ];

  const values = [
    {id:'v-wisdom',name:'Wisdom',color:'#6b7f8e'},{id:'v-auth',name:'Authenticity',color:'#a0727e'},{id:'v-conn',name:'Connections',color:'#c47832'},
    {id:'v-free',name:'Freedom',color:'#d4a44c'},{id:'v-creat',name:'Creativity',color:'#b08968'},{id:'v-exp',name:'Massive Exposure to Experiences',color:'#7f916a'},
    {id:'v-health',name:'Health / Rigour',color:'#8a9a6a'},{id:'v-spirit',name:'Spirituality',color:'#8a7f9e'},{id:'v-awe',name:'Awe for Life',color:'#c9a46a'},{id:'v-indep',name:'Independence',color:'#8a8d8f'},
  ].map(v => ({...v, fields:{embody:[],hundred:[],motivation:[],counterfeit:[]}}));
  const vf = (id, k, text, n=60) => byId(values,id).fields[k].push({date:ago(n), text});
  vf('v-free','embody',"I say no to things that pay well and cost my mornings. I own less than fits in two bags plus a bookshelf. I can leave a city in a week and I have, more than once.");
  vf('v-free','embody',"I wake without an alarm most days. My calendar has white space I defend.",300);
  vf('v-free','hundred',"A base I chose, work I chose, a schedule I set, and the financial margin to say no for six months without fear.");
  vf('v-free','motivation',"Reread the Lisbon notebook. Remember the 47th floor. Keep the monthly-burn number visible.");
  vf('v-free','counterfeit',"Restlessness. Leaving before the conversation gets hard and calling it freedom. Freedom *from* is not freedom *to*.");
  vf('v-auth','embody',"I tell the truth about what I want in the first conversation, not the fourth. My online self and my kitchen-table self are the same person.");
  vf('v-auth','counterfeit',"Stubbornness dressed as integrity. 'Just being honest' as a licence for cruelty.");
  vf('v-conn','embody',"I call people on their birthdays without prompts. I know my neighbours' names. I can sit with someone crying without fixing.");
  vf('v-conn','counterfeit',"People-pleasing. Being liked is not being close.");
  vf('v-exp','counterfeit',"Scrolling. Consuming experience second-hand and feeling full.");
  vf('v-exp','embody',"Each month I do one thing I've never done. I say yes to the strange invitation.");
  vf('v-indep','counterfeit',"Isolation. Refusing help so nobody can see me need it.");
  vf('v-health','embody',"I run three times a week and sleep seven hours. My body is a colleague, not a vehicle.");
  vf('v-health','counterfeit',"Punishment routines. Optimising the body as one more exam to pass.");
  vf('v-spirit','embody',"Thirty minutes each morning at the screen of my own mind. I notice synchronicities and write them down.");
  vf('v-creat','embody',"I ship something small every week — a photo, a paragraph, a drink recipe.");
  vf('v-awe','embody',"I stop for the light. Every day there's a moment I would have photographed even without a camera.");
  vf('v-wisdom','embody',"I change my mind in public. I reread my old narratives and update them without shame.");
  const valueOrder = ['v-free','v-auth','v-creat','v-conn','v-health','v-exp','v-awe','v-wisdom','v-spirit','v-indep'];
  const valueOrderHistory = [{date:ago(500),order:['v-exp','v-free','v-indep','v-creat','v-auth','v-conn','v-awe','v-wisdom','v-health','v-spirit']},{date:ago(120),order:valueOrder}];
  const snap = (n, r, note='') => ({id:uid(), date:ago(n), ratings:r, note});
  const valueSnapshots = [
    snap(720,{'v-wisdom':55,'v-auth':60,'v-conn':50,'v-free':82,'v-creat':60,'v-exp':95,'v-health':55,'v-spirit':40,'v-awe':80,'v-indep':85},'Osaka. Living out of a bag. Exposure maxed, connection thin.'),
    snap(540,{'v-wisdom':58,'v-auth':66,'v-conn':62,'v-free':78,'v-creat':58,'v-exp':85,'v-health':50,'v-spirit':45,'v-awe':78,'v-indep':78}),
    snap(360,{'v-wisdom':62,'v-auth':70,'v-conn':80,'v-free':58,'v-creat':52,'v-exp':60,'v-health':52,'v-spirit':55,'v-awe':70,'v-indep':55},'First winter together. Freedom dropped, connection soared. Worth it.'),
    snap(180,{'v-wisdom':66,'v-auth':74,'v-conn':84,'v-free':52,'v-creat':60,'v-exp':55,'v-health':60,'v-spirit':62,'v-awe':72,'v-indep':52}),
    Object.assign(snap(90,{'v-wisdom':68,'v-auth':76,'v-conn':82,'v-free':48,'v-creat':66,'v-exp':50,'v-health':64,'v-spirit':68,'v-awe':74,'v-indep':54},'Started the Morning Theatre. Spirituality climbing.'),{notes:{'v-spirit':'Twelve mornings in a row at the screen. Something is moving.'}}),
    snap(30,{'v-wisdom':70,'v-auth':78,'v-conn':80,'v-free':42,'v-creat':71,'v-exp':48,'v-health':66,'v-spirit':72,'v-awe':75,'v-indep':56}),
    Object.assign(snap(3,{'v-wisdom':71,'v-auth':79,'v-conn':81,'v-free':42,'v-creat':74,'v-exp':46,'v-health':68,'v-spirit':74,'v-awe':76,'v-indep':57},'Freedom is the gap. Everything else is climbing.'),{notes:{'v-creat':'Three shipped things this week. The newsletter tier is real now.','v-exp':'Same three streets for a month. Chosen, but still.'}}),
  ];

  const visionEras = [{id:'wander',name:'The Wander Years',subtitle:'Everything I could get my hands on.',startYear:2022,endYear:2024,color:'#d4a44c',order:0,type:'past',stageRef:'s6'},{id:'20s',name:'Building the base',subtitle:'Exposure, escape, and the first real choices.',startYear:2024,endYear:2028,color:'#7f916a',order:1,type:'present',stageRef:'s8'},{id:'30s',name:'30s',subtitle:'A base, a craft, a family. Depth over breadth.',startYear:2028,endYear:2038,color:'#6b7f8e',order:2,type:'future',stageRef:null},{id:'40s',name:'40s+',subtitle:'Mastery, stewardship, the long game.',startYear:2038,endYear:null,color:'#b08968',order:3,type:'future',stageRef:null}];
  const V = (o) => Object.assign({id:'',name:'',era:'20s',parentId:null,status:'pending',phase:'in-progress',progress:0,startedAt:'',completedAt:'',successCriteria:'',reflection:'',archived:false,confidence:'exploring',nextAction:'',sensory:{see:'',hear:'',smell:'',firstHour:'',who:'',noLonger:''},futureMemory:'',futureMemoryHistory:[],costs:'',currentReality:'',currentRealityHistory:[],resistance:[],preSkills:[],selfImage:'',values:[],obituary:'',evidence:[],feeling:0,targetDate:'',location:'',money:'',createdAt:ago(200)}, o);
  const visions = [
    V({id:'vi-lisbon',name:'A season in a real kitchen',era:'wander',confidence:'lived',status:'completed',completedAt:'2023-03-01',startedAt:'2022-10-01',progress:100,reflection:'Six months of onions. I learned that speed is attention with the fear removed, and that my hands could think.',values:['v-exp','v-health'],preSkills:['sk-cook'],createdAt:'2022-09-01'}),
    V({id:'vi-osaka',name:'Work behind a bar in Japan',era:'wander',confidence:'lived',status:'completed',completedAt:'2023-09-01',startedAt:'2023-04-01',progress:100,reflection:'The Namba year. The eleven-seat idea was born on a napkin at 3am.',values:['v-exp','v-conn'],preSkills:['sk-mixology','sk-jp-conv'],createdAt:'2023-03-01'}),
    V({id:'vi-jet',name:'JET Programme',era:'20s',confidence:'committed',phase:'in-progress',progress:60,startedAt:'2026-05-01',successCriteria:'An offer letter, a placement in Kansai, a start date in my calendar.',nextAction:'Ask Prof. Lin for the second reference letter by Friday.',targetDate:'2027-07-31',location:'Anywhere in Kansai, ideally Nara',money:'¥3.36M/yr',
      sensory:{see:'A staff room with a kettle, a stack of worksheets with my handwriting, a window onto a rice field going gold.',hear:'The 8am chime, students shouting "sensei!" across a corridor, the vending machine outside the gym.',smell:'Chalk dust and tatami and the curry the cafeteria makes on Wednesdays.',firstHour:'Bike to school in the cold. Bow to the vice principal. Hot canned coffee. Prepare one lesson I actually care about.',who:'Thirty-five second-years. A supervising teacher who is kind and tired. Her, on weekends, learning the trains with me.',noLonger:'Refreshing job boards. Explaining to relatives what a "gap" is.'},
      futureMemory:"I remember the first morning, the bicycle, the cold on my knuckles. I remember thinking: I chose this, on purpose, with my own hands. The kids didn't care about my CV. They cared whether I could pronounce their names. I learned all thirty-five in a week.",
      futureMemoryHistory:[{date:ago(150),text:"I got into JET and moved to Japan. It was a great year and I learned a lot of Japanese."}],
      costs:"A year of low income. Distance from her, unless she comes — and asking her to come is its own cost. Delaying the master's by at least a year.",
      currentReality:"Application submitted. One reference in, one outstanding. Interview likely in January. Japanese at N3-ish, conversational but clumsy. Savings cover four months. She has said she'd visit but not that she'd move.",
      currentRealityHistory:[{date:ago(120),text:"Application half-drafted. Haven't asked for references. Japanese at N4."}],
      resistance:[{text:"Belief: 'teaching is a step down for someone with my credentials' — Approval thread, still running.",threadId:'t-approval'},{text:"Fear that leaving again is just Escape wearing a new coat.",threadId:'t-escape'}],
      preSkills:['sk-jp-conv'],selfImage:"Someone who is useful in a room without being the smartest person in it. Patient. Funny in a second language.",values:['v-exp','v-free','v-conn'],obituary:"Because it's the first door I'd open toward a life in Japan, and because thirty-five kids would learn that a foreigner can be kind.",
      evidence:[{date:ago(40),text:'Ran into a former JET at the climbing gym. Unprompted, she offered to review my statement.'},{date:ago(12),text:'Prof. Lin replied within an hour. "Of course."'}],feeling:4}),
    V({id:'vi-fluent',name:'Fluent Japanese',era:'20s',parentId:'vi-jet',confidence:'in motion',phase:'in-progress',progress:45,startedAt:'2025-01-10',successCriteria:'N2 passed. A joke that lands in a Japanese kitchen.',nextAction:'Finish Genki II chapter 18; book the N2 for December.',targetDate:'2027-12-01',money:'',
      sensory:{see:'A paperback novel with no furigana, my thumb halfway through.',hear:'Myself making a joke in a Japanese kitchen and the whole line laughing.',smell:'',firstHour:'Morning news on the radio while I make coffee, understanding it without translating.',who:'The bar regulars. Her parents, eventually.',noLonger:'Nodding and pretending.'},
      futureMemory:"I remember the night the joke landed. It was nothing — a pun on 'nama' — but the chef repeated it to the next customer and I realised I existed in this language now.",
      costs:"An hour a day, every day, for two more years. Fewer nights out. The humility of being stupid in public.",
      currentReality:"N3 passed in July. ~1,100 kanji. Can hold a 20-minute conversation about daily life; fall apart on anything abstract. 40-day study streak, broken twice this year.",
      resistance:[{text:"Plateau shame — I've been 'intermediate' for a year and the Dabbler in me wants a new hobby.",threadId:'t-rigour'}],
      preSkills:['sk-jp-conv','sk-jp-read'],selfImage:"Someone who loves the plateau. Who shows up to the desk the way a farmer shows up to the field.",values:['v-exp','v-creat','v-free','v-conn'],obituary:"A second self, built word by word. Nobody can take that from me.",
      evidence:[{date:ago(70),text:'Understood an entire episode of a drama without subtitles.'}],feeling:5}),
    V({id:'vi-masters',name:"Master's degree in Japan",era:'30s',parentId:'vi-fluent',confidence:'plan',successCriteria:'Enrolled in a programme I am curious about, funded, in Kyoto or Tokyo.',nextAction:'Email three labs at Waseda and Kyoto with a two-paragraph pitch.',targetDate:'2028-04-01',location:'Kyoto, if I can',money:'MEXT scholarship, ¥144k/mo',
      sensory:{see:'A small seminar room, six of us, a whiteboard full of half-Japanese half-English diagrams.',hear:'The Kamo river at night, on the walk home.',smell:'Old paper in the library stacks. Kerosene heater in winter.',firstHour:'',who:'A supervisor who argues with me. Cohort friends from four countries.',noLonger:'Wondering whether law was the only serious thing I could have done.'},
      futureMemory:"",costs:"Two years of student income. Time away from any bar. Her career, if she comes; the relationship, if she doesn't.",
      currentReality:"Nothing formal. A shortlist of five programs. MEXT deadline is in nine months. Haven't contacted anyone. Research interest is real but unarticulated.",
      resistance:[{text:"Not sure I'm 'academic enough' — Rule-era belief that I'm a performer not a thinker.",threadId:'t-approval'}],
      preSkills:['sk-jp-read'],selfImage:"",values:['v-wisdom','v-exp','v-creat'],obituary:"",evidence:[],feeling:2}),
    V({id:'vi-base',name:'Finding the base location',era:'30s',confidence:'exploring',nextAction:'Spend a working week in Kagurazaka in November; note rents and light.',targetDate:'2029-01-01',location:'Tokyo (Kagurazaka / Koenji) or Kyoto',money:'',
      sensory:{see:'One street I know by heart. A door with my name on it, in two scripts.',hear:'The same crows every morning.',smell:'Rain on the same pavement, year after year.',firstHour:'',who:'',noLonger:'Packing.'},
      futureMemory:"",costs:"Wander ends. Some doors close permanently. My parents get a nine-hour flight instead of a two-hour one.",
      currentReality:"Living in her apartment. No lease in my name anywhere. Three candidate neighbourhoods, one visited.",
      resistance:[{text:"Rootedness reads as trap to the Escape thread.",threadId:'t-escape'}],preSkills:[],selfImage:"Someone who stays. Who fixes the thing instead of leaving it.",values:['v-free','v-conn','v-indep'],obituary:"A place my children would call home.",evidence:[{date:ago(200),text:'A stranger in Kagurazaka said "you look like you live here." I didn\'t, yet.'}],feeling:3}),
    V({id:'vi-bar',name:'A bar with eleven seats',era:'30s',parentId:'vi-base',confidence:'hunch',successCriteria:'Eleven stools, a lease in my name, a first regular who comes back.',nextAction:'Write the one-page concept. Just the page.',targetDate:'',location:'Kagurazaka',money:'¥8M startup',
      sensory:{see:'Eleven stools. A wall of backlit bottles that I chose one at a time. Her handwriting on the menu.',hear:'Ice. Fishmans on the speaker, quietly. Someone laughing at the far end.',smell:'Yuzu peel and old wood.',firstHour:'Polish glasses. Prep citrus. The best hour of the day, before anyone comes.',who:'Regulars. Two are friends I haven\'t met yet.',noLonger:'Wondering what my hands are for.'},
      futureMemory:"I remember the opening night, and that we ran out of ice, and that nobody minded.",
      costs:"Capital. Evenings and weekends for years. Any pretence of a conventional career. Her patience.",currentReality:"A notebook with sketches. Three years of bartending experience across two countries. No capital, no licence, no location.",
      resistance:[{text:"'Who do you think you are' — the Rule thread's voice.",threadId:'t-approval'}],preSkills:['sk-mixology','sk-jp-conv'],selfImage:"A host. Someone whose room people want to be in.",values:['v-creat','v-conn','v-indep','v-awe'],obituary:"Because I would have made a small warm place in a large cold city.",evidence:[],feeling:4}),
    V({id:'vi-family',name:'Building a family',era:'30s',confidence:'exploring',nextAction:'Have the conversation about timelines. The real one.',targetDate:'',location:'',money:'',
      sensory:{see:'',hear:'',smell:'',firstHour:'Small feet on a wooden floor. Someone needs me before I need coffee.',who:'Her. A child with her eyes. My mother, finally relaxed.',noLonger:'Treating my life as a solo project.'},
      futureMemory:"",costs:"Everything, apparently. The bar timeline, the master's timeline, sleep, the illusion of control.",currentReality:"Two years together. We've talked around it, not about it. I'm 28. She's 29. Neither of us knows what we'd need to feel ready.",
      resistance:[{text:"Fear of becoming my father's version of a father.",threadId:'t-rigour'},{text:"Being Seen: a child would see everything.",threadId:'t-seen'}],preSkills:[],selfImage:"Someone who is safe to need.",values:['v-conn','v-awe','v-auth'],obituary:"Obviously.",evidence:[],feeling:3}),
    V({id:'vi-money',name:'Financial independence via multiple streams',era:'30s',confidence:'plan',nextAction:'Ship the first paid newsletter tier this month.',targetDate:'2030-01-01',location:'',money:'¥600k/mo across 4+ streams',
      sensory:{see:'A dashboard with four green lines, none of them a salary.',hear:'',smell:'',firstHour:'',who:'',noLonger:'Doing anything purely for the invoice.'},
      futureMemory:"",costs:"Years of building at low return. Boredom with admin. The risk of turning every hobby into a shop.",currentReality:"Freelance writing ~¥180k/mo. Photography occasional. Newsletter free, 340 subscribers. No product.",
      resistance:[{text:"Wattles: I still half-believe money and creativity are opposed.",threadId:null}],preSkills:['sk-writing','sk-webdev'],selfImage:"A craftsman with a shop, not an employee with a hobby.",values:['v-free','v-indep','v-creat'],obituary:"It buys the rest of the list.",evidence:[{date:ago(25),text:'A reader asked, unprompted, whether they could pay for the newsletter.'}],feeling:3}),
    V({id:'vi-body',name:'A body that lasts',era:'20s',confidence:'in motion',phase:'documenting',progress:30,startedAt:'2025-06-01',nextAction:'Book the physio for the left shoulder.',targetDate:'',location:'',money:'',
      sensory:{see:'Myself at 50 on a climbing wall, not competing, just moving well.',hear:'My breathing on a long run, steady.',smell:'Cold morning air.',firstHour:'Wake without pain. Move for thirty minutes before the screen.',who:'',noLonger:'Apologising to my back.'},
      futureMemory:"I remember turning forty and running the river route, and that it felt exactly like turning twenty-eight.",costs:"Sleep before 11. Fewer late shifts. Some vanity — this is about function, not the mirror.",currentReality:"Run 3x/week, climb 1x. Shoulder impingement since spring, ignored. Sleep average 6h40.",
      resistance:[{text:"Health/Rigour counterfeit: turning the body into another exam.",threadId:'t-rigour'}],preSkills:['sk-climb','sk-run'],selfImage:"Someone whose body is a colleague, not a vehicle.",values:['v-health','v-free','v-awe'],obituary:"Because every other vision needs it.",evidence:[],feeling:4}),
  ];

  const skills = [
    {id:'sk-jp-conv',name:'Conversational Japanese',cat:'Languages',currentLevel:3,prereqs:[],planned:false,
      levels:[
        {number:1,label:'Kana',description:'Hiragana, katakana, greetings.',criteria:['Read a menu without romaji','Introduce myself in three sentences'],resources:[{title:'Tofugu hiragana guide',url:'https://www.tofugu.com/japanese/learn-hiragana/',type:'article'}],estimatedTime:'1 month',targetDate:null},
        {number:2,label:'Daily life',description:'A 5-minute chat about daily topics.',criteria:['Order food and ask for the bill','Talk about my week for two minutes'],resources:[{title:'Genki I',url:'https://genki3.japantimes.co.jp/en/',type:'book'}],estimatedTime:'4 months',targetDate:null},
        {number:3,label:'Conversational',description:'A 20-minute conversation with some abstraction.',criteria:['Explain why I left law, in Japanese','Follow a drama episode without subtitles'],resources:[{title:'Genki II',url:'https://genki3.japantimes.co.jp/en/',type:'book'},{title:'Nihongo con Teppei',url:'https://nihongoconteppei.com/',type:'video'}],estimatedTime:'8 months',targetDate:null},
        {number:4,label:'Functional (N2)',description:'N2 — functional in a work environment.',criteria:['Pass N2','Run a bar shift entirely in Japanese','Read an NHK article cold'],resources:[{title:'Shin Kanzen Master N2',url:'https://www.3anet.co.jp/np/en/',type:'book'},{title:'Anki',url:'https://apps.ankiweb.net/',type:'tool'}],estimatedTime:'12 months',targetDate:'2027-12-01'},
        {number:5,label:'Literate (N1+)',description:'N1+ — funny, formal, literate.',criteria:['Make a pun a chef repeats','Write a formal email without checking'],resources:[],estimatedTime:'2 years',targetDate:null}],
      milestones:[{levelTarget:4,by:'2027-12-01',note:'Before the JET placement starts'},{levelTarget:5,by:'2029-04-01',note:'Master\'s seminar in Japanese'}]},
    {id:'sk-jp-read',name:'Reading Japanese',cat:'Languages',rubric:['Kana + 100 kanji','Menus, signs, simple manga','News with a dictionary','Novels slowly','Literature, legal text'],level:2,target:4,targetDate:'2028-04-01',prereqs:['sk-jp-conv'],planned:false},
    {id:'sk-jp-biz',name:'Business Japanese',cat:'Languages',rubric:['Keigo basics','Emails','Meetings','Negotiation','Presentations'],level:0,target:3,targetDate:'',prereqs:['sk-jp-conv','sk-jp-read'],planned:true},
    {id:'sk-mandarin',name:'Mandarin (maintenance)',cat:'Languages',rubric:['Household','Conversational','Reads news','Writes essays','Literary'],level:3,target:3,targetDate:'',prereqs:[],planned:false},
    {id:'sk-webdev',name:'Web development',cat:'Technical',rubric:['HTML/CSS pages','Interactive JS apps','Full-stack with a database','Ships products people pay for','Architects systems'],level:2,target:3,targetDate:'2027-06-01',prereqs:[],planned:false},
    {id:'sk-data',name:'Data analysis',cat:'Technical',rubric:['Spreadsheets','Python basics','Clean + visualise real data','Statistical reasoning','Research-grade'],level:1,target:3,targetDate:'',prereqs:['sk-webdev'],planned:false},
    {id:'sk-writing',name:'Essay writing',cat:'Creative',rubric:['Clear paragraphs','A voice','Publishable pieces','Readers who pay','A book'],level:3,target:4,targetDate:'2027-01-01',prereqs:[],planned:false},
    {id:'sk-photo',name:'Photography',cat:'Creative',rubric:['Auto mode','Manual exposure','A consistent eye','Paid work','Exhibitions'],level:3,target:3,targetDate:'',prereqs:[],planned:false},
    {id:'sk-piano',name:'Piano (reclaimed)',cat:'Creative',rubric:['Remember the scales','Play for pleasure, 3 pieces','Improvise','Accompany singers','Compose'],level:1,target:2,targetDate:'',prereqs:[],planned:false},
    {id:'sk-run',name:'Running',cat:'Physical',rubric:['5k','10k comfortably','Half marathon','Marathon','Ultra / lifelong'],level:2,target:3,targetDate:addDays(T,21),prereqs:[],planned:false},
    {id:'sk-climb',name:'Climbing',cat:'Physical',rubric:['Top rope','Lead indoors','5.11 / V4','Outdoor lead','Multi-pitch'],level:2,target:3,targetDate:'',prereqs:[],planned:false},
    {id:'sk-hosting',name:'Hosting a room',cat:'Social',rubric:['Remember names','Make one stranger comfortable','Run a dinner for 8','Run a room of 30','People come back for the host'],level:3,target:5,targetDate:'',prereqs:[],planned:false},
    {id:'sk-listen',name:'Deep listening',cat:'Social',rubric:['Wait my turn','Reflect back','Notice what is not said','Hold silence','Be a mirror'],level:2,target:4,targetDate:'',prereqs:[],planned:false},
    {id:'sk-mixology',name:'Mixology',cat:'Craft',rubric:['Classics from memory','Balance by taste','Original recipes','A menu with a point of view','A bar people travel for'],level:3,target:5,targetDate:'2030-01-01',prereqs:[],planned:false},
    {id:'sk-cook',name:'Cooking (Japanese home)',cat:'Craft',rubric:['Rice + miso','Ten dishes','Seasonal cooking','Feed twelve','Teach it'],level:2,target:3,targetDate:'',prereqs:[],planned:false},
    {id:'sk-legal-jp',name:'Legal Japanese',cat:'Languages',rubric:['Vocabulary','Reads contracts','Drafts','Advises','Litigates'],level:0,target:1,targetDate:'',prereqs:['sk-jp-biz'],planned:true},
  ];

  const projects = [
    {id:'p-site',name:'Life Instrument',desc:'This site. A house for a life examined and a life deliberately created.',tags:['code','writing'],status:'active',link:'',income:{model:'',current:0,target:0,milestones:[]},createdAt:ago(60)},
    {id:'p-news',name:'Slow Letters',desc:'A fortnightly newsletter on craft, cities, and learning things badly on purpose.',tags:['writing'],status:'active',link:'https://example.com',income:{model:'subscriptions',current:0,target:120000,milestones:[{date:ago(300),text:'First 100 subscribers'},{date:ago(25),text:'First reader asked to pay'}]},createdAt:ago(400)},
    {id:'p-zine',name:'Osaka Nights (photo zine)',desc:'Forty photographs from the Namba bar year. Risograph, 100 copies.',tags:['visual'],status:'paused',link:'',income:{model:'product sales',current:0,target:30000,milestones:[]},createdAt:ago(500)},
    {id:'p-freelance',name:'Freelance writing',desc:'Essays and copy for three clients. The stream that pays the rent.',tags:['writing'],status:'active',link:'',income:{model:'freelance',current:180000,target:200000,milestones:[{date:ago(700),text:'First dollar'},{date:ago(600),text:'First repeat client'},{date:ago(200),text:'First referral'}]},createdAt:ago(720)},
    {id:'p-jpapp',name:'Kanji by Neighbourhood',desc:'A tiny web app that teaches kanji via Tokyo street signs.',tags:['code','visual'],status:'idea',link:'',income:{model:'',current:0,target:0,milestones:[]},createdAt:ago(90)},
    {id:'p-bar',name:'Bar concept: 十一 (eleven)',desc:'The one-page concept, the menu drafts, the spreadsheet of doom.',tags:['craft','writing'],status:'active',link:'',income:{model:'',current:0,target:600000,milestones:[]},createdAt:ago(150)},
    {id:'p-piano',name:'Reclaiming the piano',desc:'Three pieces, for nobody.',tags:['music'],status:'paused',link:'',income:{model:'',current:0,target:0,milestones:[]},createdAt:ago(240)},
    {id:'p-oldsite',name:'Portfolio v1',desc:'The old photography portfolio. Shipped, done, resting.',tags:['visual','code'],status:'shipped',link:'https://example.com',income:{model:'',current:0,target:0,milestones:[]},createdAt:ago(800)},
  ];
  const nods = [];
  const nodTexts = {'p-site':['Built the timeline spine','Vision tree branch layout','Wrote seed narratives','Fixed the radar chart','Styled the morning theatre','Habit rings'],'p-news':['Drafted issue #41','Edited the Lisbon piece','Replied to reader mail','Outlined the paid tier'],'p-freelance':['Client B draft','Invoice sent','Revisions for the agency','Call with new client'],'p-bar':['Sketched the bar layout','Costed the backbar','Wrote three drink specs','Read a book on small-bar economics'],'p-zine':['Selected 12 more frames'],'p-piano':['Scales, ten minutes']};
  const nodP = {'p-site':.7,'p-news':.35,'p-freelance':.5,'p-bar':.25,'p-zine':.04,'p-piano':.06};
  const nodE = {'p-site':4.2,'p-news':3.9,'p-freelance':2.3,'p-bar':4.6,'p-zine':3.5,'p-piano':4.0};
  for(let d=84; d>=0; d--) for(const pid of Object.keys(nodP)) if(rnd() < nodP[pid]){ const txts = nodTexts[pid]; nods.push({id:uid(),projectId:pid,text:txts[Math.floor(rnd()*txts.length)],duration:['15min','30min','1hr','2hr'][Math.floor(rnd()*4)],link:'',energy:clamp(Math.round(nodE[pid] + (rnd()-.5)*2),1,5),date:ago(d)}); }
  const ideas = [{id:uid(),text:'A walking tour of Tokyo bars that closed, narrated by their last bartenders'},{id:uid(),text:'Field recordings of rice cookers across Asia'},{id:uid(),text:'Teach a "learning things badly" workshop'}];

  const H = (o,i) => Object.assign({id:'h'+i,name:'',freq:{type:'daily',days:[],count:0},timeOfDay:'anytime',dimension:'physical',kind:'expenditure',links:{values:[],visions:[],skills:[]},min:'',ideal:'',prompt:'',negative:false,archived:false,stackAfter:null,order:i}, o);
  const habits = [
    H({name:'Morning Theatre visualization',dimension:'mental',kind:'expenditure',timeOfDay:'morning',min:'5 minutes, eyes closed',ideal:'30 minutes at the screen',prompt:'What did you see?',links:{values:['v-spirit'],visions:['vi-jet','vi-bar'],skills:[]}},1),
    H({name:'Read Definite Chief Aim aloud',dimension:'spiritual',kind:'recovery',timeOfDay:'morning',min:'Once',ideal:'Morning and night, with feeling',stackAfter:'h1',links:{values:['v-spirit'],visions:[],skills:[]}},2),
    H({name:'30 min Japanese',dimension:'mental',kind:'expenditure',timeOfDay:'morning',min:'10 flashcards',ideal:'30 min Genki + shadowing',stackAfter:'h2',prompt:'What word surprised you?',links:{values:['v-exp'],visions:['vi-fluent'],skills:['sk-jp-conv']}},3),
    H({name:'Morning run',dimension:'physical',kind:'expenditure',timeOfDay:'morning',freq:{type:'days',days:[1,3,5],count:0},min:'Walk 15 min',ideal:'6k river route',prompt:'How was the run?',links:{values:['v-health'],visions:['vi-body'],skills:['sk-run']}},4),
    H({name:'Sleep by 11pm',dimension:'physical',kind:'recovery',timeOfDay:'evening',min:'In bed by 11:30',ideal:'Lights out 11:00',links:{values:['v-health'],visions:['vi-body'],skills:[]}},5),
    H({name:'Gratitude entry',dimension:'emotional',kind:'recovery',timeOfDay:'evening',min:'One line',ideal:'Three, with detail',prompt:'What was it?',links:{values:['v-awe'],visions:[],skills:[]}},6),
    H({name:'Call someone I love',dimension:'emotional',kind:'expenditure',timeOfDay:'anytime',freq:{type:'perWeek',days:[],count:3},min:'A voice note',ideal:'A real call',links:{values:['v-conn'],visions:['vi-family'],skills:['sk-listen']}},7),
    H({name:'5 min meditation',dimension:'spiritual',kind:'recovery',timeOfDay:'afternoon',min:'Three breaths',ideal:'5 minutes',links:{values:['v-spirit'],visions:[],skills:[]}},8),
    H({name:'Ship one small thing',dimension:'mental',kind:'expenditure',timeOfDay:'afternoon',freq:{type:'perWeek',days:[],count:1},min:'Post one photo',ideal:'Publish something',links:{values:['v-creat'],visions:['vi-money'],skills:['sk-writing']}},9),
    H({name:'Climbing session',dimension:'physical',kind:'expenditure',timeOfDay:'evening',freq:{type:'perWeek',days:[],count:1},min:'Hangboard 10 min',ideal:'2 hours at the gym',links:{values:['v-health'],visions:['vi-body'],skills:['sk-climb']}},10),
    H({name:'Evening walk, no phone',dimension:'spiritual',kind:'recovery',timeOfDay:'evening',min:'Around the block',ideal:'30 minutes',links:{values:['v-awe'],visions:[],skills:[]}},11),
    H({name:'Doomscrolling',dimension:'mental',kind:'expenditure',timeOfDay:'anytime',negative:true,links:{values:['v-exp'],visions:[],skills:[]}},12),
  ];
  const habitLog = {};
  const hp = {h1:.75,h2:.7,h3:.65,h4:.8,h5:.5,h6:.6,h7:.4,h8:.55,h9:.8,h10:.85,h11:.45};
  for(let d=95; d>=1; d--){ const day = ago(d); const dow = parseDay(day).getDay(); habitLog[day] = {}; for(const h of habits){ if(h.negative) continue; const due = h.freq.type==='daily' || (h.freq.type==='days' && h.freq.days.includes(dow)) || (h.freq.type==='perWeek' && rnd() < h.freq.count/7*1.6); if(!due) continue; const r = rnd(); if(r < hp[h.id]*(d<40?1.1:.85)) habitLog[day][h.id] = {level: rnd()<.25?'min':'full', note:''}; } }
  habitLog[ago(1)] = {...habitLog[ago(1)], h1:{level:'full',note:'Saw the bar. Ice. The far-end laugh.'}, h2:{level:'full',note:''}};
  const negLast = {h12: ago(9)};

  const checkins = {};
  const sentences = ['Slow morning, good coffee, the shoulder is talking.','Wrote for three hours and forgot to eat. Best kind of day.','Grey. Called my mother. Better after.','JET reference came through. Walked the long way home.','Argued about the future. Made up over dumplings.','Climbed badly, laughed a lot.','Quiet. The kind of quiet from Solitude — the good kind.','Tired. Did the minimum. That counts.','Tokyo dream very loud today.','A stranger complimented the newsletter. Held it all day.'];
  for(let d=30; d>=1; d--){ const base = 14 + Math.sin(d/5)*2.5 + (rnd()-.5)*3; checkins[ago(d)] = {mood:clamp(Math.round(3 + Math.sin(d/4)*1.2 + (rnd()-.5)*1.5),1,5), sentence: rnd()<.6 ? sentences[Math.floor(rnd()*sentences.length)] : '', energy:{physical:clamp(Math.round(3+Math.sin(d/3)+(rnd()-.5)*2),1,5),emotional:clamp(Math.round(3.5+Math.cos(d/6)+(rnd()-.5)*2),1,5),mental:clamp(Math.round(4+(rnd()-.5)*2),1,5),spiritual:clamp(Math.round(2.5+d/-30*-1.5+(rnd()-.5)*2),1,5)}, setpoint:clamp(Math.round(base),1,22), intention:''}; }
  checkins[ago(1)].intention = 'Ask Prof. Lin for the second reference. Nothing else matters today.';
  checkins[ago(1)].sentence = 'JET reference came through. Walked the long way home.';

  const E = (o) => Object.assign({id:uid(),type:'reflection',title:'',body:'',occurredAt:T,createdAt:ts(0),media:[],links:{stages:[],substages:[],threads:[],values:[],visions:[],skills:[],projects:[]},people:[],places:[],emotions:[],confidence:'',extra:{}}, o);
  const L = (o) => Object.assign({stages:[],substages:[],threads:[],values:[],visions:[],skills:[],projects:[]}, o);
  const entries = [
    // memories per stage
    E({type:'memory',title:'The stolen mango',body:"Over the neighbour's fence, under the tin roof, a mango so ripe it split when I held it. My grandmother pretended not to see. That was the first time I understood that rules had gaps and that some adults would guard the gaps for you.",occurredAt:'Summer 2002',createdAt:ts(380),links:L({stages:['s1'],substages:['s1a'],threads:['t-rigour'],values:[{id:'v-free',pol:'+'},{id:'v-awe',pol:'+'}]}),people:['Grandmother'],places:['The courtyard'],extra:{installed:'Belief: the world has gaps, and joy lives in them. Also: someone will cover for you if you\'re sweet about it — the seed of Approval.'}}),
    E({type:'memory',title:'The metronome',body:"Grade 5 piano. My teacher set the metronome and left the room. I played the Chopin at exactly the right tempo for forty minutes with tears running into my collar, because I'd been told crying didn't count if you kept playing.",occurredAt:'2009-03',createdAt:ts(370),links:L({stages:['s2'],substages:['s2a'],threads:['t-approval','t-rigour'],values:[{id:'v-auth',pol:'-'},{id:'v-health',pol:'+'}]}),extra:{installed:'Pattern: performance continues regardless of internal state. Useful under pressure; corrosive as a default. This is the Rigour pole.'}}),
    E({type:'memory',title:'The clap',body:"Regional olympiad, second place. Two hundred strangers applauding. I remember the feeling more precisely than the maths. I remember thinking: I want this again, forever.",occurredAt:'2010-11',createdAt:ts(365),links:L({stages:['s2'],substages:['s2b'],threads:['t-approval'],values:[{id:'v-conn',pol:'-'}]}),extra:{installed:'Belief: attention from strangers is the highest reward. The engine of Clout.'}}),
    E({type:'memory',title:'The list',body:"Notebook #4. A list titled 'things I actually like', written at 1am after a family dinner where I'd said nothing true. Fourteen items. Twelve of them are still true. None of them were on my CV.",occurredAt:'2013-10',createdAt:ts(350),links:L({stages:['s3'],substages:['s3b'],threads:['t-seen'],values:[{id:'v-auth',pol:'+'},{id:'v-wisdom',pol:'+'}]}),extra:{installed:'Capability: writing to find out what I think. Belief: there is a real self underneath the performed one, and it can be reached with a pen.'}}),
    E({type:'memory',title:'The river route',body:"I started walking home the long way, forty minutes past the river, headphones in. Nobody knew where I was for forty minutes a day. It was the first territory that was entirely mine.",occurredAt:'2013–2014',createdAt:ts(345),links:L({stages:['s3'],substages:['s3a'],threads:['t-escape'],values:[{id:'v-indep',pol:'+'},{id:'v-spirit',pol:'+'}]}),extra:{installed:'Pattern: solitude as a place I go to, not a place I\'m left in. The good version of Escape.'}}),
    E({type:'memory',title:'Lockdown, day 40',body:"I finished the exam prep for the week by Tuesday. Wednesday I sat on the floor of my room and realised I did not know what I did when nobody needed anything from me. I watched the wall for an hour. Then I opened the old notebooks.",occurredAt:'2020-05',createdAt:ts(330),links:L({stages:['s4'],substages:['s4b'],threads:['t-approval','t-seen'],values:[{id:'v-wisdom',pol:'+'},{id:'v-exp',pol:'-'}]}),extra:{installed:'Fear: that without an audience I am nobody. Also the first crack in that fear.'}}),
    E({type:'memory',title:'The moot',body:"I won the moot court final. Walked out of the building with the trophy in a tote bag, sat on a bench, and felt precisely nothing. Not relief, not pride. The nothing was the loudest thing I'd ever heard.",occurredAt:'2021-11',createdAt:ts(320),links:L({stages:['s5'],substages:['s5a'],threads:['t-approval'],values:[{id:'v-auth',pol:'-'},{id:'v-wisdom',pol:'+'}]}),extra:{installed:'Belief: emotional flatness after a win is data, not a malfunction. I finally learned to read the instrument.'}}),
    E({type:'memory',title:'The partner\'s boat',body:"He showed me photos of the boat. Forty minutes. He hadn't been on it in two years. I looked at his eyes and saw the 47th floor reflected in them, and nothing else.",occurredAt:'2022-07',createdAt:ts(315),links:L({stages:['s5'],substages:['s5b'],threads:['t-escape','t-leaving'],values:[{id:'v-free',pol:'-'}]}),extra:{installed:'A picture of a future I would not accept at any price. Sometimes the most useful vision is the negative one.'}}),
    E({type:'memory',title:'Onions',body:"Six hundred onions on my first day in the Lisbon kitchen. By the end my hands knew something my head didn't. Chef said: 'Speed is attention with the fear removed.' I've thought about that sentence every week since.",occurredAt:'2022-10',createdAt:ts(300),links:L({stages:['s6'],substages:['s6a'],threads:['t-rigour'],values:[{id:'v-exp',pol:'+'},{id:'v-health',pol:'+'}]}),people:['Chef Rui'],places:['Lisbon'],extra:{installed:'Capability: physical craft as a form of thinking. Belief: rigour can be play if the fear is gone.'}}),
    E({type:'memory',title:'3am, Namba',body:"Wiping the counter after the last customer. The chef-owner poured two glasses and said, in Japanese I mostly understood: 'You look like someone who should have his own place.' I said nothing. I went home and drew eleven stools on a napkin.",occurredAt:'2023-06',createdAt:ts(290),links:L({stages:['s6'],substages:['s6b'],threads:['t-seen'],values:[{id:'v-creat',pol:'+'},{id:'v-conn',pol:'+'}],visions:['vi-bar']}),places:['Osaka'],extra:{installed:'A vision. And a proof that being seen by a stranger can plant one.'}}),
    E({type:'memory',title:'First fall',body:"Yangshuo, a 5.9 I should have finished. Fell, caught, hung there over the river with the karst going gold. Laughed until the belayer asked if I was okay. I was more okay than I'd been in years.",occurredAt:'2023-11',createdAt:ts(280),links:L({stages:['s6'],substages:['s6c'],threads:['t-rigour'],values:[{id:'v-awe',pol:'+'},{id:'v-health',pol:'+'}],skills:['sk-climb']}),extra:{installed:'Belief: failure in the body is survivable and even joyful. The Obsessive in me lost some grip that day.'}}),
    E({type:'memory',title:'She didn\'t look away',body:"I told her the thing about the metronome. The whole thing. She didn't say anything reassuring. She just kept looking at me. I had never been looked at through a story before.",occurredAt:'2024-09',createdAt:ts(260),links:L({stages:['s7'],substages:['s7a'],threads:['t-seen','t-approval'],values:[{id:'v-conn',pol:'+'},{id:'v-auth',pol:'+'}]}),extra:{installed:'Belief: I can be known without being impressive. The first real counter-evidence to the Approval thread.'}}),
    E({type:'memory',title:'The argument about the future',body:"Our first real fight. Japan versus here. I noticed halfway through that I was arguing to win — moot court voice — and stopped. Said: I don't know. She said: finally.",occurredAt:'2025-03',createdAt:ts(180),links:L({stages:['s7'],substages:['s7a'],threads:['t-leaving','t-seen'],values:[{id:'v-auth',pol:'+'},{id:'v-free',pol:'-'}],visions:['vi-family','vi-base']}),extra:{installed:'Capability: losing on purpose. Pattern noticed: Leaving activates whenever Belonging gets specific.'}}),
    // reflections
    E({type:'reflection',title:'On the plateau',body:"Leonard says love the plateau. I've been at N3 for eleven months. What I notice is that the plateau is where the Dabbler and the Hacker in me negotiate: the Dabbler wants a new language, the Hacker says N3 is fine for a bar. Neither of them is the Master. The Master just does Chapter 18.",occurredAt:ago(8),createdAt:ts(8),links:L({visions:['vi-fluent'],skills:['sk-jp-conv'],threads:['t-rigour'],values:[{id:'v-wisdom',pol:'+'}]})}),
    E({type:'reflection',title:'Structural tension, felt',body:"Held both pictures this morning: the eleven-seat bar, and the actual notebook with three sketches and no money. Didn't flinch from either. Fritz is right — the discomfort has a direction. It points at the one-page concept I keep not writing.",occurredAt:ago(3),createdAt:ts(3),links:L({visions:['vi-bar'],projects:['p-bar'],values:[{id:'v-creat',pol:'+'}]})}),
    E({type:'reflection',title:'Freedom at 42%',body:"The gap analysis says Freedom is my #1 value and my lowest congruence. That's not a contradiction; it's a diagnosis. I've traded freedom for connection this year, on purpose. The question isn't how to get it back — it's what freedom looks like *with* rootedness, not instead of it.",occurredAt:ago(15),createdAt:ts(15),links:L({values:[{id:'v-free',pol:'-'},{id:'v-conn',pol:'+'}],visions:['vi-base'],threads:['t-escape']})}),
    E({type:'reflection',title:'Winning feeling, located',body:"Maltz says find a past success and weld the feeling to the future. Mine is the Namba counter at 3am. Not the compliment — the wiping. The feeling of a room I had closed well.",occurredAt:ago(22),createdAt:ts(22),links:L({stages:['s6'],visions:['vi-bar'],values:[{id:'v-spirit',pol:'+'}]})}),
    // synchronicity
    E({type:'synchronicity',title:'The former JET at the gym',body:"Was thinking about the JET statement on the wall. Came down, and the woman on the next rope mentioned she'd done JET in Nara. Nara. The prefecture I'd written 'ideally' next to that morning.",occurredAt:ago(40),createdAt:ts(40),links:L({visions:['vi-jet'],values:[{id:'v-awe',pol:'+'}]}),extra:{preceded:'Two days of visualising the staff room. The first time I\'d done it with smell.',read:'That specificity is a signal the field responds to. Or that I talk about Japan too much at the gym. Both.',revisit:true}}),
    E({type:'synchronicity',title:'"You look like you live here"',body:"Kagurazaka, first visit. An old woman outside a tofu shop said it in passing. I had been there forty minutes.",occurredAt:ago(200),createdAt:ts(200),links:L({visions:['vi-base'],places:['Kagurazaka']}),extra:{preceded:'',read:'Nothing yet. Filed.',revisit:true}}),
    E({type:'synchronicity',title:'Fishmans in the supermarket',body:"Long Season playing in a Tokyo supermarket at 11pm. Nobody plays Fishmans in a supermarket. I stood in the noodle aisle for the full 35 minutes.",occurredAt:ago(95),createdAt:ts(95),links:L({stages:['s6'],visions:['vi-bar']}),extra:{preceded:'Had just told her the bar would only ever play one album.',read:'The bar is listening.',revisit:false}}),
    // manifestation
    E({type:'manifestation',title:'A reader who pays',body:"Intention set in March: one reader, unprompted, asks to pay for the newsletter.",occurredAt:ago(170),createdAt:ts(170),links:L({visions:['vi-money'],projects:['p-news']}),extra:{status:'arrived',evidence:[{date:ago(25),text:'Email from a reader in Berlin: "is there a way to pay you for this?"'}]}}),
    E({type:'manifestation',title:'The second reference',body:"Prof. Lin says yes without hesitation.",occurredAt:ago(30),createdAt:ts(30),links:L({visions:['vi-jet']}),extra:{status:'arrived',evidence:[{date:ago(12),text:'Replied within the hour. "Of course."'}]}}),
    E({type:'manifestation',title:'Eleven seats',body:"The right room in Kagurazaka, at a rent that isn't insane, with a landlord who likes bars.",occurredAt:ago(100),createdAt:ts(100),links:L({visions:['vi-bar','vi-base']}),extra:{status:'held',evidence:[]}}),
    E({type:'manifestation',title:'A supervisor who argues with me',body:"Someone at Kyoto or Waseda replies to the pitch with a real objection.",occurredAt:ago(50),createdAt:ts(50),links:L({visions:['vi-masters']}),extra:{status:'evidence appearing',evidence:[{date:ago(14),text:'Found a paper by a Kyoto lab that disagrees with exactly my premise. That\'s the person.'}]}}),
    // gratitude
    E({type:'gratitude',title:'',body:"The rice cooker song. Her, humming it back. The window open in September.",occurredAt:ago(1),createdAt:ts(1),links:L({values:[{id:'v-awe',pol:'+'},{id:'v-conn',pol:'+'}]})}),
    E({type:'gratitude',title:'',body:"Prof. Lin. A reader in Berlin. A shoulder that still lets me climb, mostly.",occurredAt:ago(4),createdAt:ts(4),links:L({values:[{id:'v-conn',pol:'+'}]})}),
    E({type:'gratitude',title:'',body:"That I left the glass building. Every single day, that.",occurredAt:ago(11),createdAt:ts(11),links:L({stages:['s5'],values:[{id:'v-free',pol:'+'}]})}),
    // dreams
    E({type:'dream',title:'The bar with no door',body:"Eleven seats, all full, but I couldn't find the door to get behind the counter. Kept walking around the outside. Someone inside was making my drinks.",occurredAt:ago(6),createdAt:ts(6),links:L({visions:['vi-bar'],threads:['t-approval']}),extra:{vivid:4,recurring:true,symbols:['bar','door','outside']}}),
    E({type:'dream',title:'The exam in Japanese',body:"Sitting the bar exam but every question was in Japanese and I understood all of it. Woke up disappointed it was law.",occurredAt:ago(33),createdAt:ts(33),links:L({stages:['s5'],visions:['vi-fluent']}),extra:{vivid:3,recurring:false,symbols:['exam','language']}}),
    // quotes
    E({type:'quote',title:'',body:"Your nervous system cannot tell the difference between an actual experience and one that is vividly imagined.",occurredAt:ago(80),createdAt:ts(80),links:L({visions:['vi-jet']}),extra:{source:'Psycho-Cybernetics',author:'Maxwell Maltz',page:'Ch. 3',why:'Because it means the Morning Theatre is not a metaphor. It is practice.'}}),
    E({type:'quote',title:'',body:"The master of any game is generally a master of practice.",occurredAt:ago(60),createdAt:ts(60),links:L({skills:['sk-jp-conv']}),extra:{source:'Mastery',author:'George Leonard',page:'',why:'The plateau, again. I keep needing to hear it.'}}),
    E({type:'quote',title:'',body:"Speed is attention with the fear removed.",occurredAt:'2022-10',createdAt:ts(300),links:L({stages:['s6'],threads:['t-rigour']}),extra:{source:'Chef Rui, Lisbon',author:'Rui',page:'',why:'The single most useful sentence anyone has said to me about work.'}}),
    E({type:'quote',title:'',body:"Energy, not time, is the fundamental currency of high performance.",occurredAt:ago(45),createdAt:ts(45),links:L({values:[{id:'v-health',pol:'+'}]}),extra:{source:'The Power of Full Engagement',author:'Loehr & Schwartz',page:'p. 4',why:'It explains why the 47th floor was fatal and the Lisbon kitchen was not, despite the same hours.'}}),
    E({type:'quote',title:'',body:"A belief is only a thought you keep thinking.",occurredAt:ago(20),createdAt:ts(20),links:L({threads:['t-approval']}),extra:{source:'Ask and It Is Given',author:'Esther & Jerry Hicks',page:'',why:'Approval is a thought I have kept thinking since 2009. I can stop.'}}),
    // questions
    E({type:'question',title:'Is Tokyo a base or an escape?',body:"How would I know the difference from the inside?",occurredAt:ago(150),createdAt:ts(150),links:L({visions:['vi-base'],threads:['t-escape']}),extra:{answers:[{date:ago(100),text:'If I\'d go even if she came — base. If I\'d go *because* it\'s far — escape.'},{date:ago(20),text:'Update: I\'d go slower if she came. That\'s new. That\'s base.'}]}}),
    E({type:'question',title:'What would I do if I could never be applauded again?',body:"",occurredAt:ago(300),createdAt:ts(300),links:L({threads:['t-approval']}),extra:{answers:[{date:ago(280),text:'Bartend. Cook. Write letters nobody publishes. (This list is suspiciously close to the Vision Tree.)'}]}}),
    E({type:'question',title:'Do I want a child or do I want to be the kind of person who has one?',body:"",occurredAt:ago(60),createdAt:ts(60),links:L({visions:['vi-family'],threads:['t-seen']}),extra:{answers:[]}}),
    E({type:'question',title:'What is my research question, actually?',body:"Not the fundable one. The real one.",occurredAt:ago(45),createdAt:ts(45),links:L({visions:['vi-masters']}),extra:{answers:[]}}),
    // progress
    E({type:'progress',title:'Genki II ch. 17 done',body:"Causative-passive. Shadowed the dialogue six times. Still slow on the abstract stuff.",occurredAt:ago(2),createdAt:ts(2),links:L({skills:['sk-jp-conv'],visions:['vi-fluent']}),extra:{duration:45}}),
    E({type:'progress',title:'Read a whole NHK Easy article cold',body:"No dictionary. Understood 90%.",occurredAt:ago(9),createdAt:ts(9),links:L({skills:['sk-jp-read'],visions:['vi-fluent']}),extra:{duration:20}}),
    E({type:'progress',title:'Long run, 10k',body:"River route twice. Shoulder fine, knees fine, mind fine.",occurredAt:ago(5),createdAt:ts(5),links:L({skills:['sk-run'],visions:['vi-body']}),extra:{duration:58}}),
    E({type:'progress',title:'Sent the V4',body:"Finally. Three months on it.",occurredAt:ago(13),createdAt:ts(13),links:L({skills:['sk-climb'],visions:['vi-body']}),extra:{duration:120}}),
    E({type:'progress',title:'New drink: 柚子 sour',body:"Yuzu, shochu, egg white, a bitters I made from the bar-year leftovers. Balanced by taste on the third try.",occurredAt:ago(18),createdAt:ts(18),links:L({skills:['sk-mixology'],visions:['vi-bar'],projects:['p-bar']}),extra:{duration:90}}),
    E({type:'progress',title:'Built the vision tree layout',body:"Recursive branch placement, sway animation. This site.",occurredAt:ago(7),createdAt:ts(7),links:L({skills:['sk-webdev'],projects:['p-site']}),extra:{duration:180}}),
    E({type:'progress',title:'Essay draft: On the plateau',body:"1,800 words. It has a shape.",occurredAt:ago(16),createdAt:ts(16),links:L({skills:['sk-writing'],projects:['p-news']}),extra:{duration:120}}),
    E({type:'progress',title:'Dinner for eight',body:"Fed eight people Japanese home food. Only burned the tamagoyaki.",occurredAt:ago(27),createdAt:ts(27),links:L({skills:['sk-cook','sk-hosting'],visions:['vi-bar']}),extra:{duration:240}}),
    E({type:'progress',title:'Photographed the market at dawn',body:"Forty frames. Four keepers.",occurredAt:ago(120),createdAt:ts(120),links:L({skills:['sk-photo'],projects:['p-zine']}),extra:{duration:90}}),
    E({type:'progress',title:'Scales, ten minutes',body:"Fingers remembered more than I did.",occurredAt:ago(140),createdAt:ts(140),links:L({skills:['sk-piano'],projects:['p-piano']}),extra:{duration:10}}),
    // visualization
    E({type:'visualization',title:'The staff room, with smell',body:"Twenty-five minutes. Chalk dust, curry, the kettle. Saw myself learning the thirty-five names. Felt the winning feeling from Namba welded to it — the room I close well.",occurredAt:ago(1),createdAt:ts(1),links:L({visions:['vi-jet'],values:[{id:'v-spirit',pol:'+'}]})}),
    E({type:'visualization',title:'Opening night',body:"Ran out of ice. Nobody minded. Twenty minutes. Strong emotion — Hicks would call it Positive Expectation.",occurredAt:ago(4),createdAt:ts(4),links:L({visions:['vi-bar']})}),
    E({type:'lifeevent',title:'',body:"Last shift at the Namba bar. Chef gave me a bottle of the house shochu and said 'come back with a place of your own.'",occurredAt:'2023-09-14',createdAt:ts(720),links:L({stages:['s6']}),extra:{eraId:'wander'}}),
    E({type:'lifeevent',title:'',body:'Moved into her apartment. Two bags and a bookshelf. The rice cooker sings at 7:10 every morning.',occurredAt:'2024-11-02',createdAt:ts(670),links:L({stages:['s7']}),extra:{eraId:'20s'}}),
    E({type:'lifeevent',title:'',body:'Passed N3 in Osaka. Celebrated with takoyaki and a nap.',occurredAt:ago(60),createdAt:ts(60),links:L({skills:['sk-jp-conv']}),extra:{eraId:'20s'}}),
    E({type:'lifeevent',title:'',body:'Prof. Lin said yes to the reference within the hour. Walked the long way home.',occurredAt:ago(12),createdAt:ts(12),links:L({visions:['vi-jet']}),extra:{eraId:'20s'}}),
    // letters (the year-ahead one)
    E({type:'letter',title:'To myself, one year from now',body:"By the time you read this you'll know about JET. Whichever way it went, I hope you asked the family question out loud. I hope the shoulder is fixed. I hope you still walk the long way home.",occurredAt:addDays(T,365),createdAt:ts(10),links:L({stages:['s8'],visions:['vi-jet','vi-family']})}),
    // an artifact entry
    E({type:'artifact',title:'The napkin',body:"Eleven stools, drawn at 3:40am in Namba. Kept in the passport.",occurredAt:'2023-06',createdAt:ts(290),links:L({stages:['s6'],visions:['vi-bar']})}),
  ];
  // on-this-day entries from previous years
  const d = parseDay(T);
  entries.push(E({type:'reflection',title:'A year ago today',body:"Took the train to Kagurazaka for the first time with no plan. Sat in a tiny bar with nine seats and counted them twice. Thought: two more.",occurredAt:`${d.getFullYear()-1}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,createdAt:ts(365),links:L({visions:['vi-bar','vi-base']})}));
  entries.push(E({type:'reflection',title:'Two years ago today',body:"Last shift at the Namba bar. Chef gave me a bottle of the house shochu and said 'come back with a place of your own.' I'm trying.",occurredAt:`${d.getFullYear()-2}-${pad(d.getMonth()+1)}-${pad(d.getDate()+1 > 28 ? 27 : d.getDate()+1)}`,createdAt:ts(730),links:L({stages:['s6'],visions:['vi-bar']})}));

  return {
    version:1,
    settings:{theme:'dark',sound:false,feltTime:false,home:'home',chapterNamed:false,ribbons:true,firstOpen:T},
    reminders:[], stages, threads, tensions, values, valueOrder, valueOrderHistory, valueSnapshots, visionEras, visions, skills, projects, nods, ideas, habits, habitLog, negLast, checkins, entries,
    journals:[{type:'synchronicity',name:'Synchronicity'},{type:'manifestation',name:'Manifestation'},{type:'reflection',name:'Reflections'},{type:'gratitude',name:'Gratitude'},{type:'dream',name:'Dreams'},{type:'quote',name:'Quotes & Marginalia'},{type:'question',name:'Open Questions'},{type:'visualization',name:'Visualizations'},{type:'letter',name:'Letters'},{type:'lifeevent',name:'Life events'}],
    theatre:{
      script:"I am someone who builds small warm rooms in large cold cities. I move through my mornings unhurried; I have already decided what matters. I speak Japanese with my whole face. I am useful in rooms without needing to be the smartest person in them. When someone looks at me through a story, I let them. My body is a colleague I respect. I close every room well.\n\nI see myself behind a counter, polishing a glass, the far end of the bar laughing at something I said in a second language. I feel the weight of the glass. I smell yuzu. This is not a wish. This is a memory I haven't reached yet.",
      winning:"Namba, 3am, wiping the counter after the last customer. Not the compliment — the wiping. A room I had closed well. Chest open, shoulders down, nothing left to prove. I can find that feeling in about four seconds if I start with the cloth in my hand.",
      aim:"By 1 April 2028 I will be living in Japan with a functional N2, enrolled in a master's I am curious about, running a monthly income of ¥400,000 from at least three streams. In return I will give one honest hour a day to the language, one shipped thing a week, and my full attention to the people in front of me.",
      cycleStart:ago(13), days:[ago(13),ago(12),ago(11),ago(10),ago(9),ago(7),ago(6),ago(5),ago(4),ago(3),ago(2),ago(1)]
    },
    reviews:{lastWeekly:ago(5),lastSeasonal:ago(50),lastAnnual:ago(250)},
    people:['Grandmother','Chef Rui','Prof. Lin'], places:['The courtyard','Lisbon','Osaka','Kagurazaka'],
  };
}
